name: BubbleShield
author: squidicuz
version: 0.9.91
main: net.sqdmc.bubbleshield.BubbleShield
depend: [Factions]

commands:
  bubbleshield:
    description: Reload configuration
    aliases: [bs]
    usage: |
      /bubbleshield reload
    permission: bubbleshield.admin

permissions:
  bubbleshield.admin:
    default: op
  bubbleshield.create.player:
    default: true
  bubbleshield.create.faction:
    default: true